'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, BookOpen, ChevronRight, Compass, FlaskConical, Globe2, Heart, Menu, Sparkles, X } from 'lucide-react';
import { products, type Product } from '@/lib/products';
import { JourneyStage, PathFinder, ProductDetails } from './interactive';
import { ArrowLeft, ExternalLink, RotateCcw, Search, Star } from 'lucide-react';
const initials: Record<string,string> = { hallium:'한', kmate:'K', video:'늘', drama:'극' };
function ProductCard({product,onInspect,saved,onSave}:{product:Product,onInspect:(p:Product)=>void,saved:boolean,onSave:(id:string)=>void}) {
 return <article className={'product-card '+product.accent}>
  <div className="card-head"><span className="mono">{product.number} / {product.category}</span><button className={'nui-save '+(saved?'saved':'')} onClick={()=>onSave(product.id)} aria-pressed={saved} aria-label={(saved?'Remove ':'Save ')+product.name+(saved?' from':' to')+' saved experiences'} title={saved?'Remove from saved':'Save for later'}><Star size={17} fill={saved?'currentColor':'none'}/></button></div>
  <button className="nui-card-preview" onClick={()=>onInspect(product)} aria-label={'Preview '+product.name}><span className={'product-icon '+product.accent}>{initials[product.id]}</span><span>Take a peek <ArrowUpRight size={15}/></span></button>
  <p className="eyebrow">{product.kicker}</p><h3>{product.name}</h3><p className="description">{product.description}</p>
  <div className="tags">{product.features.map(f=><span key={f}>{f}</span>)}</div>
  <div className="card-foot"><button className="nui-card-more" onClick={()=>onInspect(product)}>Discover more <ArrowUpRight size={16}/></button>{product.href?<a className="nui-card-launch" href={product.href} target="_blank" rel="noopener noreferrer" aria-label={'Open '+product.name+' in a new tab'}><ExternalLink size={17}/></a>:<span className="nui-pending">LINK SOON</span>}</div>
 </article>;
}
export default function Hub() {
 const [view, setView] = useState<'home'|'dashboard'>('home');
 const [menu, setMenu] = useState(false);
 const [filter, setFilter] = useState('All');
 const [query,setQuery]=useState('');
 const [saved,setSaved]=useState<string[]>([]);
 const [modal,setModal]=useState<Product|null>(null);
 const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const value=JSON.parse(localStorage.getItem('nuri.saved-products')||'[]');if(Array.isArray(value))setSaved(value.filter((v:unknown):v is string=>typeof v==='string'))}catch{}if(location.hash==='#hub')setView('dashboard');const pop=()=>setView(location.hash==='#hub'?'dashboard':'home');addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&view==='dashboard'&&!modal&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();searchRef.current?.focus()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[view,modal]);
 const toggleSaved=(id:string)=>setSaved(previous=>{const next=previous.includes(id)?previous.filter(v=>v!==id):[...previous,id];try{localStorage.setItem('nuri.saved-products',JSON.stringify(next))}catch{}return next});
 const navigate = (v:'home'|'dashboard') => { if(v!==view)history.pushState({},'',v==='dashboard'?'#hub':location.pathname+location.search);setView(v);setMenu(false);window.scrollTo({top:0,behavior:'smooth'}); };
 const scroll = (id:string) => { navigate('home'); setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}),50); };
 const visible=useMemo(()=>products.filter(p=>(filter==='All'||(filter==='Language'&&p.id!=='kmate')||(filter==='Study abroad'&&p.id==='kmate')||(filter==='Saved'&&saved.includes(p.id)))&&[p.name,p.description,p.category,...p.features].join(' ').toLowerCase().includes(query.trim().toLowerCase())),[filter,saved,query]);
 return <div className="shell"><a className="skip-link" href="#main-content">Skip to content</a>
 <header className="nav wrap"><button className="brand" onClick={()=>navigate('home')} aria-label="NURI Labs home"><span className="brand-mark">n<span>✳</span></span><span>NURI<span className="brand-light">LABS</span><small>LEARN • CONNECT • GROW</small></span></button>
 <nav className={`nav-links ${menu?'show':''}`} aria-label="Primary navigation"><button className={view==='home'?'active':''} onClick={()=>navigate('home')}>Home</button><button onClick={()=>scroll('ecosystem')}>Our ecosystem</button><button onClick={()=>scroll('impact')}>Our approach</button><button className={view==='dashboard'?'active':''} onClick={()=>navigate('dashboard')}>The hub</button></nav>
 <button className="nav-cta" onClick={()=>navigate('dashboard')}>Enter the hub <ArrowUpRight size={16}/></button><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?'Close menu':'Open menu'}>{menu?<X/>:<Menu/>}</button></header>
 {view==='home'?<main id="main-content">
 <section className="hero wrap"><div className="hero-copy"><div className="announcement"><span className="pulse"/> AN INDEPENDENT STUDENT-LED INITIATIVE</div><h1>Curiosity takes<br/>you <em>places.</em><span className="hero-spark">✳</span></h1><p className="hero-sub">One connected home for learning Korean, finding your people, and exploring what comes next.</p>
 <div className="hero-actions"><button className="button-dark" onClick={()=>navigate('dashboard')}>Explore NURI Labs <ArrowUpRight size={18}/></button><button className="button-text" onClick={()=>scroll('ecosystem')}>Meet our four products <ArrowDownRight size={17}/></button></div>
 <div className="hero-caption">— MADE FOR THE CURIOUS, EVERYWHERE.</div></div><JourneyStage onInspect={setModal}/></section>
 <div className="ticker">LEARN KOREAN ✳ FIND YOUR PEOPLE ✳ BUILD YOUR FUTURE ✳ LIVE THE LANGUAGE ✳ LEARN KOREAN ✳ FIND YOUR PEOPLE ✳</div>
 <section className="section wrap" id="ecosystem"><div className="section-top"><div><span className="section-label">01 / THE ECOSYSTEM</span><h2>Different paths.<br/><em>One bigger picture.</em></h2></div><p>From your first Korean phrase to your first study-abroad application, there is a place for you here.</p></div><div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p} onInspect={setModal} saved={saved.includes(p.id)} onSave={toggleSaved}/>) }</div><p className="section-note"><Sparkles size={17}/> Each product keeps its own experience. NURI Labs brings them together.</p></section><PathFinder onInspect={setModal}/>
 <section className="story-band" id="impact"><div className="wrap story-inner"><div className="story-icon"><FlaskConical size={30}/></div><div><span className="section-label">03 / WHY WE BUILD</span><h2>Learning should feel like<br/><em>opening doors.</em></h2></div><div><p>NURI Labs is an independent student-led educational technology initiative exploring how thoughtful software can help people learn, connect and move forward.</p><button className="light-link" onClick={()=>navigate('dashboard')}>Step into the hub <ArrowUpRight size={18}/></button></div></div></section>
 <section className="closing wrap"><span className="section-label">YOUR NEXT CHAPTER STARTS HERE</span><h2>Go further,<br/><em>together.</em></h2><button className="button-dark" onClick={()=>navigate('dashboard')}>Discover your path <ArrowUpRight size={18}/></button><div className="closing-flower">✳</div></section>
 </main>:<main id="main-content" className="dashboard wrap"><button className="nui-back" onClick={()=>navigate('home')}><ArrowLeft size={16}/> Back to NURI Labs</button><div className="dash-title"><div><span className="section-label">WELCOME TO THE HUB</span><h1>Where to <em>today?</em></h1><p>Choose your next step. All of NURI's learning experiences, in one place.</p></div><div className="dash-symbol">✳</div></div>
 <div className="dash-banner"><div><span className="mono">YOUR NURI JOURNEY</span><h2>Explore something new.</h2><p>Start with a word, a story, a video or a new connection.</p></div><Compass size={78} strokeWidth={1}/></div>
 <div className="dash-toolbar"><div><span className="section-label">YOUR TOOLKIT</span><h2>Explore the ecosystem <span>04</span></h2></div><label className="nui-search"><Search size={18}/><input ref={searchRef} type="search" aria-label="Search NURI products" placeholder="Search experiences..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>/</kbd></label></div>
 <div className="filters" role="group" aria-label="Filter products">{['All','Language','Study abroad','Saved'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)} className={filter===f?'selected':''}>{f==='Saved'&&<Star size={13}/>} {f}{f==='Saved'&&saved.length?' ('+saved.length+')':''}</button>)}</div>
 {visible.length?<div className="product-grid nui-dash-grid">{visible.map(p=><ProductCard key={p.id} product={p} onInspect={setModal} saved={saved.includes(p.id)} onSave={toggleSaved}/>)}</div>:<div className="nui-no-results"><Search size={28}/><h3>Nothing on this path yet.</h3><p>Try another search or browse the full ecosystem.</p><button onClick={()=>{setFilter('All');setQuery('')}}><RotateCcw size={16}/> Clear filters</button></div>}<p className="nui-saved-note"><Star size={15}/> Saved products stay in this browser only.</p><div className="passport"><Globe2 size={31}/><div><span className="section-label">UP NEXT / LEARNING PASSPORT</span><h3>One learning journey, across every product.</h3><p>Shared progress and unified sign-in are planned for a later release. This hub does not access or combine existing account data.</p></div><span className="passport-status">PLANNED</span></div></main>}
 <footer className="footer"><div className="wrap footer-inner"><button className="brand" onClick={()=>navigate('home')}><span className="brand-mark">n<span>✳</span></span><span>NURI<span className="brand-light">LABS</span><small>LEARN • CONNECT • GROW</small></span></button><p>Made with curiosity. Built for possibility.</p><span>© {new Date().getFullYear()} NURI Labs</span></div></footer><ProductDetails product={modal} onClose={()=>setModal(null)}/></div>;
}
